from .product_detail_producer import ProductDetailProducer
from .product_detail_replies_consumer import ProductDetailRepliesConsumer
from .product_detail_results_consumer import ProductDetailResultsConsumer
